2025-09-18 15:33:39,458 : INFO : root : Loading config.
2025-09-18 15:33:39,461 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-09-18 15:33:39,462 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\cfa6ecba65704a931c9dd214c44986c8.mpf_cache
2025-09-18 15:33:39,586 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\f98ffc0ff5962effface7d86bc406d5c.mpf_cache
2025-09-18 15:33:39,587 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\91cc4d1c993c58dc354e34974b9cfeac.mpf_cache
2025-09-18 15:33:39,588 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\f98ffc0ff5962effface7d86bc406d5c.mpf_cache
2025-09-18 15:33:39,588 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\76792f1d686f89709887dba7bd69667a.mpf_cache
2025-09-18 15:33:39,589 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\142bbae4707335cc8e3efaa4364c4893.mpf_cache
2025-09-18 15:33:39,589 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\b4249e7b8f95e82c549b9263ef475a09.mpf_cache
2025-09-18 15:33:39,591 : INFO : ConfigProcessor : Loading config from file C:\Users\White\Documents\Top_Gun_Pinball\shows\.\attract_inserts_mega.yaml.
2025-09-18 15:33:39,634 : INFO : ConfigProcessor : Loading config: C:\Users\White\Documents\Top_Gun_Pinball\shows\.\attract_inserts_mega.yaml
2025-09-18 15:33:39,636 : INFO : ConfigProcessor : Config file cache created: C:\Users\White\AppData\Local\Temp\17003635873251b4f6841bf4ab3bdcdd.mpf_cache
2025-09-18 15:33:39,636 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\434e0238e97461d536537fa1d2ac13b8.mpf_cache
2025-09-18 15:33:39,637 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\5cb8a848aaedecad105d66ca86abc153.mpf_cache
2025-09-18 15:33:39,638 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\62a37c5ed70d052a3f65d3898f24f311.mpf_cache
2025-09-18 15:33:39,639 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\8de5cc7bb4cd85234067138a393db5f5.mpf_cache
2025-09-18 15:33:39,640 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev9
2025-09-18 15:33:39,640 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-09-18-15-33-39-mpf-TopGunPinball.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\White\\Documents\\Top_Gun_Pinball\\logs\\2025-09-18-15-33-39-mpf-TopGunPinball.log'}
2025-09-18 15:33:39,641 : INFO : Machine : MPF path: C:\Users\White\mpf\Lib\site-packages\mpf
2025-09-18 15:33:39,641 : INFO : Machine : Machine path: C:\Users\White\Documents\Top_Gun_Pinball
2025-09-18 15:33:39,641 : INFO : Machine : Platform: win32
2025-09-18 15:33:39,641 : INFO : Machine : Python executable location: C:\Users\White\mpf\Scripts\python.exe
2025-09-18 15:33:39,641 : INFO : Machine : Python version: 3.12.7 (64-bit)
2025-09-18 15:33:39,643 : INFO : Machine : Initializing MPF...
2025-09-18 15:33:39,758 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-09-18 15:33:39,791 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-09-18 15:33:39,791 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 61000, 'prev_value': None, 'change': True}
2025-09-18 15:33:39,791 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 73000, 'prev_value': None, 'change': True}
2025-09-18 15:33:39,791 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev9', 'prev_value': None, 'change': True}
2025-09-18 15:33:39,791 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev9, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-09-18 15:33:39,792 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.7', 'prev_value': None, 'change': True}
2025-09-18 15:33:39,973 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-09-18 15:33:39,973 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-09-18 15:33:39,973 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2025-09-18 15:33:39,974 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-09-18 15:33:39,974 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-09-18 15:33:39,974 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\White\\Documents\\Top_Gun_Pinball\\logs\\2025-09-18-15-33-39-mpf-TopGunPinball.log', 'prev_value': None, 'change': True}
2025-09-18 15:33:39,974 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-09-18 15:33:40,026 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-09-18 15:33:40,026 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-0', <Platform.Virtual>) <switch.s_trough_1>
2025-09-18 15:33:40,026 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-1', <Platform.Virtual>) <switch.s_trough_2>
2025-09-18 15:33:40,026 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-2', <Platform.Virtual>) <switch.s_trough_3>
2025-09-18 15:33:40,026 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-3', <Platform.Virtual>) <switch.s_trough_4>
2025-09-18 15:33:40,026 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-4', <Platform.Virtual>) <switch.s_trough_5>
2025-09-18 15:33:40,026 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-5', <Platform.Virtual>) <switch.s_trough_6>
2025-09-18 15:33:40,029 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2025-09-18 15:33:40,033 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2025-09-18 15:33:40,044 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2025-09-18 15:33:40,044 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2025-09-18 15:33:40,045 : INFO : ball_device.bd_plunger : BCH: Initial count: 0
2025-09-18 15:33:40,045 : INFO : ball_device.bd_plunger : State: idle
2025-09-18 15:33:40,045 : INFO : ball_device.bd_trough : BCH: Initial count: 6
2025-09-18 15:33:40,045 : INFO : ball_device.bd_trough : State: idle
2025-09-18 15:33:40,046 : INFO : ball_device.bd_lock_elevator : BCH: Initial count: 0
2025-09-18 15:33:40,046 : INFO : ball_device.bd_lock_elevator : State: idle
2025-09-18 15:33:40,046 : INFO : ball_device.bd_mode_scoop : BCH: Initial count: 0
2025-09-18 15:33:40,046 : INFO : ball_device.bd_mode_scoop : State: idle
2025-09-18 15:33:40,061 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2025-09-18 15:33:40,095 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...lor #550000')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...lor #550000')>)>
Traceback (most recent call last):
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 122, in _convert_color
    color = RGBColor(color)
            ^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 177, in __init__
    self._color = RGBColor.string_to_rgb(color)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 420, in string_to_rgb
    raise ColorException("Invalid RGB string: {}".format(value))
mpf.core.rgb_color.ColorException: Invalid RGB string: #550000

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\White\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 83, in _validate_config_item
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 80, in _validate_config_item
    device_settings = self._expand_device_config(device_settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 133, in _expand_device_config
    device_settings['color'] = self._convert_color(color)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 124, in _convert_color
    self.raise_config_error("Invalid color {}".format(color), 1, source_exception=e, context=context)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\logging.py", line 175, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "attract_inserts_mega" >> Failed to load config player attract_inserts_mega:lights with settings {'l_mig_i': 'red', 'l_mig_m': '#550000'} >> Failed to expand entry "l_mig_m". >> Invalid color #550000 Error Code: CFE-light_player-1 (https://missionpinball.org/logs)
2025-09-18 15:33:40,140 : INFO : Machine : Starting the main run loop with active modes: []
2025-09-18 15:33:40,141 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-09-18 15:33:40,141 : INFO : Machine : Shutting down...
2025-09-18 15:33:40,141 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-09-18 15:33:41,154 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 122, in _convert_color
    color = RGBColor(color)
            ^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 177, in __init__
    self._color = RGBColor.string_to_rgb(color)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\rgb_color.py", line 420, in string_to_rgb
    raise ColorException("Invalid RGB string: {}".format(value))
mpf.core.rgb_color.ColorException: Invalid RGB string: #550000

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "C:\Users\White\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 171, in load
    self._process_step_actions(step, actions)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 201, in _process_step_actions
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\assets\show.py", line 197, in _process_step_actions
    self.machine.show_controller.show_players[key].validate_config_entry(value, self.name)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 83, in _validate_config_item
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 80, in _validate_config_item
    device_settings = self._expand_device_config(device_settings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 133, in _expand_device_config
    device_settings['color'] = self._convert_color(color)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\light_player.py", line 124, in _convert_color
    self.raise_config_error("Invalid color {}".format(color), 1, source_exception=e, context=context)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\logging.py", line 175, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in light_player: Show "attract_inserts_mega" >> Failed to load config player attract_inserts_mega:lights with settings {'l_mig_i': 'red', 'l_mig_m': '#550000'} >> Failed to expand entry "l_mig_m". >> Invalid color #550000 Error Code: CFE-light_player-1 (https://missionpinball.org/logs)
2025-09-18 15:33:41,156 : INFO : root : MPF run loop ended.
