2025-09-18 16:26:30,307 : INFO : root : Loading config.
2025-09-18 16:26:30,312 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2025-09-18 16:26:30,312 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\cfa6ecba65704a931c9dd214c44986c8.mpf_cache
2025-09-18 16:26:30,444 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\White\Documents\Top_Gun_Pinball\modes\attract\config\attract.yaml
2025-09-18 16:26:30,444 : INFO : ConfigProcessor : Loading config from file C:\Users\White\mpf\Lib\site-packages\mpf\modes\attract\config\attract.yaml.
2025-09-18 16:26:30,448 : INFO : ConfigProcessor : Loading config: C:\Users\White\mpf\Lib\site-packages\mpf\modes\attract\config\attract.yaml
2025-09-18 16:26:30,448 : INFO : ConfigProcessor : Loading config from file C:\Users\White\Documents\Top_Gun_Pinball\modes\attract\config\attract.yaml.
2025-09-18 16:26:30,465 : INFO : ConfigProcessor : Loading config: C:\Users\White\Documents\Top_Gun_Pinball\modes\attract\config\attract.yaml
2025-09-18 16:26:30,466 : INFO : ConfigProcessor : Config file cache created: C:\Users\White\AppData\Local\Temp\f98ffc0ff5962effface7d86bc406d5c.mpf_cache
2025-09-18 16:26:30,466 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\91cc4d1c993c58dc354e34974b9cfeac.mpf_cache
2025-09-18 16:26:30,467 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\f98ffc0ff5962effface7d86bc406d5c.mpf_cache
2025-09-18 16:26:30,479 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\76792f1d686f89709887dba7bd69667a.mpf_cache
2025-09-18 16:26:30,479 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\142bbae4707335cc8e3efaa4364c4893.mpf_cache
2025-09-18 16:26:30,480 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\b4249e7b8f95e82c549b9263ef475a09.mpf_cache
2025-09-18 16:26:30,481 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\17003635873251b4f6841bf4ab3bdcdd.mpf_cache
2025-09-18 16:26:30,481 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\434e0238e97461d536537fa1d2ac13b8.mpf_cache
2025-09-18 16:26:30,482 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\5cb8a848aaedecad105d66ca86abc153.mpf_cache
2025-09-18 16:26:30,482 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\62a37c5ed70d052a3f65d3898f24f311.mpf_cache
2025-09-18 16:26:30,483 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\58d7809d3d969de03aaf131fc45863f8.mpf_cache
2025-09-18 16:26:30,496 : INFO : ConfigProcessor : Loading config from cache: C:\Users\White\AppData\Local\Temp\8de5cc7bb4cd85234067138a393db5f5.mpf_cache
2025-09-18 16:26:30,498 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev9
2025-09-18 16:26:30,498 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2025-09-18-16-26-30-mpf-TopGunPinball.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\White\\Documents\\Top_Gun_Pinball\\logs\\2025-09-18-16-26-30-mpf-TopGunPinball.log'}
2025-09-18 16:26:30,498 : INFO : Machine : MPF path: C:\Users\White\mpf\Lib\site-packages\mpf
2025-09-18 16:26:30,498 : INFO : Machine : Machine path: C:\Users\White\Documents\Top_Gun_Pinball
2025-09-18 16:26:30,498 : INFO : Machine : Platform: win32
2025-09-18 16:26:30,498 : INFO : Machine : Python executable location: C:\Users\White\mpf\Scripts\python.exe
2025-09-18 16:26:30,498 : INFO : Machine : Python version: 3.12.7 (64-bit)
2025-09-18 16:26:30,501 : INFO : Machine : Initializing MPF...
2025-09-18 16:26:30,609 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2025-09-18 16:26:30,640 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2025-09-18 16:26:30,641 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 61000, 'prev_value': None, 'change': True}
2025-09-18 16:26:30,641 : INFO : EventManager : Event: ======'machine_var_player2_score'====== Args={'value': 73000, 'prev_value': None, 'change': True}
2025-09-18 16:26:30,641 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev9', 'prev_value': None, 'change': True}
2025-09-18 16:26:30,641 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev9, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2025-09-18 16:26:30,641 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.7', 'prev_value': None, 'change': True}
2025-09-18 16:26:30,817 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.26100-SP0', 'prev_value': None, 'change': True}
2025-09-18 16:26:30,818 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2025-09-18 16:26:30,818 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2025-09-18 16:26:30,818 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.26100', 'prev_value': None, 'change': True}
2025-09-18 16:26:30,818 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2025-09-18 16:26:30,818 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\White\\Documents\\Top_Gun_Pinball\\logs\\2025-09-18-16-26-30-mpf-TopGunPinball.log', 'prev_value': None, 'change': True}
2025-09-18 16:26:30,818 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2025-09-18 16:26:30,867 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2025-09-18 16:26:30,869 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-0', <Platform.Virtual>) <switch.s_trough_1>
2025-09-18 16:26:30,869 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-1', <Platform.Virtual>) <switch.s_trough_2>
2025-09-18 16:26:30,869 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-2', <Platform.Virtual>) <switch.s_trough_3>
2025-09-18 16:26:30,869 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-3', <Platform.Virtual>) <switch.s_trough_4>
2025-09-18 16:26:30,869 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-4', <Platform.Virtual>) <switch.s_trough_5>
2025-09-18 16:26:30,869 : INFO : SwitchController : Found active switch: ('playfield_board_lower-3208-5', <Platform.Virtual>) <switch.s_trough_6>
2025-09-18 16:26:30,871 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe...our config.')>)
handle: <Handle EventManager._queue_task_done(<Task finishe...our config.')>)>
Traceback (most recent call last):
  File "C:\Users\White\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 78, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_player.py", line 144, in _parse_config
    return self.get_full_config(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_player.py", line 216, in get_full_config
    return self.machine.config_validator.validate_config(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 243, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:shows with settings {'rainbow_breathe': {'loops': 3, 'speed': <NativeTemplate 1.0>, 'priority': 200, 'block_queue': True, 'show_queue': 'attract_cycle', 'action': 'play', 'show': None, 'start_step': <NativeTemplate 1>, 'start_running': <Template True>, 'sync_ms': None, 'manual_advance': False}, 'spinner': {'loops': 3, 'priority': 200, 'block_queue': True, 'show_queue': 'attract_cycle'}, 'wave': {'loops': 3, 'priority': 200, 'block_queue': True, 'show_queue': 'attract_cycle', 'events_when_completed': 'attract_cycle_again'}} >> Config validation error: Entry show_player:show_player:show_queue = "attract_cycle" is not valid. Device "attract_cycle" not found in "show_queues:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2025-09-18 16:26:30,914 : INFO : Machine : Starting the main run loop with active modes: []
2025-09-18 16:26:30,914 : WARNING : Machine : Attract mode is not active, game will not be playable. Please check your attract mode configuration.
2025-09-18 16:26:30,916 : INFO : Machine : Shutting down...
2025-09-18 16:26:30,916 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2025-09-18 16:26:31,920 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\machine.py", line 808, in _run_loop
    raise self._exception['exception']
  File "C:\Users\White\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 795, in _queue_task_done
    future.result()
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\mode_controller.py", line 97, in initialize_modes
    item.method(config=mode.config[item.config_section],
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_player.py", line 150, in process_mode_config
    config = self.validate_config(config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_player.py", line 113, in validate_config
    validated_config[event] = self.validate_config_entry(settings, event)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 56, in validate_config_entry
    raise e
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 52, in validate_config_entry
    self._validate_config_item(device, device_settings))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\config_players\device_config_player.py", line 78, in _validate_config_item
    device_settings = self._parse_config(device_settings, device)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_player.py", line 144, in _parse_config
    return self.get_full_config(config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_player.py", line 216, in get_full_config
    return self.machine.config_validator.validate_config(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 243, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\White\mpf\Lib\site-packages\mpf\core\config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Failed to load config player mode_attract_started:shows with settings {'rainbow_breathe': {'loops': 3, 'speed': <NativeTemplate 1.0>, 'priority': 200, 'block_queue': True, 'show_queue': 'attract_cycle', 'action': 'play', 'show': None, 'start_step': <NativeTemplate 1>, 'start_running': <Template True>, 'sync_ms': None, 'manual_advance': False}, 'spinner': {'loops': 3, 'priority': 200, 'block_queue': True, 'show_queue': 'attract_cycle'}, 'wave': {'loops': 3, 'priority': 200, 'block_queue': True, 'show_queue': 'attract_cycle', 'events_when_completed': 'attract_cycle_again'}} >> Config validation error: Entry show_player:show_player:show_queue = "attract_cycle" is not valid. Device "attract_cycle" not found in "show_queues:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2025-09-18 16:26:31,922 : INFO : root : MPF run loop ended.
